### ISSUE TITLE
GFWL exe link dead

### ISSUE THREAD

**Issue by stephenjmcmahon** [neonoxd/deckstuff#1]
Link doesn't pull the gfwl.exe correctly. An .exe is created but never launches from script. I was able to find a DL below and when renaming this file to gfwl.exe and placing it in the expected "dl" folder the script finished successfully. 

Thank you for the work on this!!!

https://drive.google.com/file/d/1dhdwHuMnTA9_SDkosZN5DJN32yVJIfLl/view

**Comment by neonoxd** [comment]
Thanks for letting me know, I fixed the link
